### ISSUE TITLE
Figure out what to do with `gray` and `light-gray` Helix colors.

### ISSUE THREAD

**Issue by igor-ramazanov** [igor-ramazanov/kak-tree-sitter-helix#5]
Helix has a list of [named colors](https://docs.helix-editor.com/themes.html#color-palettes) with the majority of them likely backed by ANSI colors.

However, there are also colors named `gray` and `light-gray` which do not correspond to any [Kakoune named ANSI colors](https://github.com/mawww/kakoune/blob/2d9c84e363d499eb699540c53d9f912f446a4d30/doc/pages/faces.asciidoc#declaration).

Figure out how it is determined in the Helix source code and implement the accompanying logic.

**Comment by igor-ramazanov** [comment]
Alacritty understands `gray` if it's used in Kakoune, however, I did't find any usage in Kakoune's source code: https://github.com/mawww/kakoune/blob/2d9c84e363d499eb699540c53d9f912f446a4d30/src/color.hh#L17

**Comment by postsolar** [comment]
Given that Helix docs list `default` + 16 colors, and `gray` comes where `white` would usually be (following the [conventional order of ANSI escape sequences](https://gist.github.com/fnky/458719343aabd01cfb17a3a4f7296797#8-16-colors)), I'm convinced it's just `white` i.e. `\x1b[37m`.

**Comment by igor-ramazanov** [comment]
@postsolar Seems like it, indeed. Although, I am not sure why there `white` defined as well if it's the same color if I understood correctly. It's at the bottom of the Helix default colors list, right after `light-gray`.

**Comment by postsolar** [comment]
Testing it manually though I can say I was wrong. `gray` is actually bright-black, and `light-gray` is `white` (color 7). Helix' white is then color 15.

**Comment by igor-ramazanov** [comment]
@postsolar Thanks!

I've found the mappings:
- [`Helix` to `crossterm-rs`](https://github.com/helix-editor/helix/blob/ebf155d6351a84dec010447af88b8246103537da/helix-view%2Fsrc%2Fgraphics.rs#L282-L300).
- [`crossterm-rs` definitions](https://github.com/crossterm-rs/crossterm/blob/99fe255f33f774f04c09755572503349c915112b/src%2Fstyle%2Ftypes%2Fcolor.rs#L17-L26).

**Comment by igor-ramazanov** [comment]
Done in https://github.com/igor-ramazanov/kak-tree-sitter-helix/pull/14
